server:
  port: 8082

#oracle 驱动
#spring.jpa.database: oracle
#spring.datasource.driver-class-name: oracle.jdbc.driver.OracleDriver
#spring.datasource.url: jdbc:oracle:thin:@//10.100.50.80:1521/orcl
#spring.datasource.username: c##admin
#spring.datasource.password: admin
#spring.jpa.hibernate.ddl-auto: update

#mysql 驱动

spring:
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_mybatis?setUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        max-active: 8
        min-idle: 0



mybatis.mapperLocations: classpath:/mapper/*.xml
mybatis.typeAliasesPackag: com.cloud.springboot.entity


spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5


#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**








