server:
  port: 8082

spring.jpa.database: oracle
spring.datasource.driver-class-name: oracle.jdbc.driver.OracleDriver
spring.datasource.url: jdbc:oracle:thin:@//10.100.50.197:1521/orcl
spring.datasource.username: c##admin
spring.datasource.password: admin
spring.jpa.hibernate.ddl-auto: update

mybatis.mapperLocations: classpath:/mapper/*.xml
mybatis.typeAliasesPackag: com.cloud.springboot.entity


spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5


#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**

#cas
cas.server-url-prefix: http://127.0.0.1:8080/cas
cas.server-login-url: http://127.0.0.1:8080/cas/login
cas.client-host-url: http://127.0.0.1:8082
cas.validation-type: CAS
cas:
  authentication-url-patterns:

