package com.cloud.springboot.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;



public class DsePipeBaseinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPE_NAME
     *
     * @mbg.generated
     */
    private String pipeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPELINE_CODE
     *
     * @mbg.generated
     */
    private String pipelineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPELINE_NAME
     *
     * @mbg.generated
     */
    private String pipelineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPE_MATERIAL
     *
     * @mbg.generated
     */
    private String pipeMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPE_LENGTH
     *
     * @mbg.generated
     */
    private BigDecimal pipeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPE_RADIUS
     *
     * @mbg.generated
     */
    private String pipeRadius;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PIPE_THICKNESS
     *
     * @mbg.generated
     */
    private Short pipeThickness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.INTERFACE_TYPE
     *
     * @mbg.generated
     */
    private String interfaceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.START_POINT
     *
     * @mbg.generated
     */
    private String startPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.END_POINT
     *
     * @mbg.generated
     */
    private String endPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.COMPANY_ID
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.INSTALL_TIME
     *
     * @mbg.generated
     */
    private Date installTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.TEMPERRATURE
     *
     * @mbg.generated
     */
    private Short temperrature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.TRANS_MEDIUM
     *
     * @mbg.generated
     */
    private String transMedium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PRESSURE
     *
     * @mbg.generated
     */
    private BigDecimal pressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.FLOW_THRESHOLD
     *
     * @mbg.generated
     */
    private BigDecimal flowThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.PRES_THRESHOLD
     *
     * @mbg.generated
     */
    private Integer presThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.DESIGN_DEPT
     *
     * @mbg.generated
     */
    private String designDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.CONSTRUCTION_DEPT
     *
     * @mbg.generated
     */
    private String constructionDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.SUPERVISOR_DEPT
     *
     * @mbg.generated
     */
    private String supervisorDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.BUILD_DEPT
     *
     * @mbg.generated
     */
    private String buildDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.LOCATION
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.USE_YEAR
     *
     * @mbg.generated
     */
    private Short useYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.LOCATION_ID
     *
     * @mbg.generated
     */
    private String locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSE_PIPE_BASEINFO.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSE_PIPE_BASEINFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.ID
     *
     * @return the value of DSE_PIPE_BASEINFO.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.ID
     *
     * @param id the value for DSE_PIPE_BASEINFO.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPE_NAME
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPE_NAME
     *
     * @mbg.generated
     */
    public String getPipeName() {
        return pipeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPE_NAME
     *
     * @param pipeName the value for DSE_PIPE_BASEINFO.PIPE_NAME
     *
     * @mbg.generated
     */
    public void setPipeName(String pipeName) {
        this.pipeName = pipeName == null ? null : pipeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.CODE
     *
     * @return the value of DSE_PIPE_BASEINFO.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.CODE
     *
     * @param code the value for DSE_PIPE_BASEINFO.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPELINE_CODE
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPELINE_CODE
     *
     * @mbg.generated
     */
    public String getPipelineCode() {
        return pipelineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPELINE_CODE
     *
     * @param pipelineCode the value for DSE_PIPE_BASEINFO.PIPELINE_CODE
     *
     * @mbg.generated
     */
    public void setPipelineCode(String pipelineCode) {
        this.pipelineCode = pipelineCode == null ? null : pipelineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPELINE_NAME
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPELINE_NAME
     *
     * @mbg.generated
     */
    public String getPipelineName() {
        return pipelineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPELINE_NAME
     *
     * @param pipelineName the value for DSE_PIPE_BASEINFO.PIPELINE_NAME
     *
     * @mbg.generated
     */
    public void setPipelineName(String pipelineName) {
        this.pipelineName = pipelineName == null ? null : pipelineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPE_MATERIAL
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPE_MATERIAL
     *
     * @mbg.generated
     */
    public String getPipeMaterial() {
        return pipeMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPE_MATERIAL
     *
     * @param pipeMaterial the value for DSE_PIPE_BASEINFO.PIPE_MATERIAL
     *
     * @mbg.generated
     */
    public void setPipeMaterial(String pipeMaterial) {
        this.pipeMaterial = pipeMaterial == null ? null : pipeMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPE_LENGTH
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPE_LENGTH
     *
     * @mbg.generated
     */
    public BigDecimal getPipeLength() {
        return pipeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPE_LENGTH
     *
     * @param pipeLength the value for DSE_PIPE_BASEINFO.PIPE_LENGTH
     *
     * @mbg.generated
     */
    public void setPipeLength(BigDecimal pipeLength) {
        this.pipeLength = pipeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPE_RADIUS
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPE_RADIUS
     *
     * @mbg.generated
     */
    public String getPipeRadius() {
        return pipeRadius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPE_RADIUS
     *
     * @param pipeRadius the value for DSE_PIPE_BASEINFO.PIPE_RADIUS
     *
     * @mbg.generated
     */
    public void setPipeRadius(String pipeRadius) {
        this.pipeRadius = pipeRadius == null ? null : pipeRadius.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PIPE_THICKNESS
     *
     * @return the value of DSE_PIPE_BASEINFO.PIPE_THICKNESS
     *
     * @mbg.generated
     */
    public Short getPipeThickness() {
        return pipeThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PIPE_THICKNESS
     *
     * @param pipeThickness the value for DSE_PIPE_BASEINFO.PIPE_THICKNESS
     *
     * @mbg.generated
     */
    public void setPipeThickness(Short pipeThickness) {
        this.pipeThickness = pipeThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.INTERFACE_TYPE
     *
     * @return the value of DSE_PIPE_BASEINFO.INTERFACE_TYPE
     *
     * @mbg.generated
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.INTERFACE_TYPE
     *
     * @param interfaceType the value for DSE_PIPE_BASEINFO.INTERFACE_TYPE
     *
     * @mbg.generated
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType == null ? null : interfaceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.START_POINT
     *
     * @return the value of DSE_PIPE_BASEINFO.START_POINT
     *
     * @mbg.generated
     */
    public String getStartPoint() {
        return startPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.START_POINT
     *
     * @param startPoint the value for DSE_PIPE_BASEINFO.START_POINT
     *
     * @mbg.generated
     */
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint == null ? null : startPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.END_POINT
     *
     * @return the value of DSE_PIPE_BASEINFO.END_POINT
     *
     * @mbg.generated
     */
    public String getEndPoint() {
        return endPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.END_POINT
     *
     * @param endPoint the value for DSE_PIPE_BASEINFO.END_POINT
     *
     * @mbg.generated
     */
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint == null ? null : endPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.COMPANY_ID
     *
     * @return the value of DSE_PIPE_BASEINFO.COMPANY_ID
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.COMPANY_ID
     *
     * @param companyId the value for DSE_PIPE_BASEINFO.COMPANY_ID
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.INSTALL_TIME
     *
     * @return the value of DSE_PIPE_BASEINFO.INSTALL_TIME
     *
     * @mbg.generated
     */
    public Date getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.INSTALL_TIME
     *
     * @param installTime the value for DSE_PIPE_BASEINFO.INSTALL_TIME
     *
     * @mbg.generated
     */
    public void setInstallTime(Date installTime) {
        this.installTime = installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.STATUS
     *
     * @return the value of DSE_PIPE_BASEINFO.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.STATUS
     *
     * @param status the value for DSE_PIPE_BASEINFO.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.TEMPERRATURE
     *
     * @return the value of DSE_PIPE_BASEINFO.TEMPERRATURE
     *
     * @mbg.generated
     */
    public Short getTemperrature() {
        return temperrature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.TEMPERRATURE
     *
     * @param temperrature the value for DSE_PIPE_BASEINFO.TEMPERRATURE
     *
     * @mbg.generated
     */
    public void setTemperrature(Short temperrature) {
        this.temperrature = temperrature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.TRANS_MEDIUM
     *
     * @return the value of DSE_PIPE_BASEINFO.TRANS_MEDIUM
     *
     * @mbg.generated
     */
    public String getTransMedium() {
        return transMedium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.TRANS_MEDIUM
     *
     * @param transMedium the value for DSE_PIPE_BASEINFO.TRANS_MEDIUM
     *
     * @mbg.generated
     */
    public void setTransMedium(String transMedium) {
        this.transMedium = transMedium == null ? null : transMedium.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PRESSURE
     *
     * @return the value of DSE_PIPE_BASEINFO.PRESSURE
     *
     * @mbg.generated
     */
    public BigDecimal getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PRESSURE
     *
     * @param pressure the value for DSE_PIPE_BASEINFO.PRESSURE
     *
     * @mbg.generated
     */
    public void setPressure(BigDecimal pressure) {
        this.pressure = pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.FLOW_THRESHOLD
     *
     * @return the value of DSE_PIPE_BASEINFO.FLOW_THRESHOLD
     *
     * @mbg.generated
     */
    public BigDecimal getFlowThreshold() {
        return flowThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.FLOW_THRESHOLD
     *
     * @param flowThreshold the value for DSE_PIPE_BASEINFO.FLOW_THRESHOLD
     *
     * @mbg.generated
     */
    public void setFlowThreshold(BigDecimal flowThreshold) {
        this.flowThreshold = flowThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.PRES_THRESHOLD
     *
     * @return the value of DSE_PIPE_BASEINFO.PRES_THRESHOLD
     *
     * @mbg.generated
     */
    public Integer getPresThreshold() {
        return presThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.PRES_THRESHOLD
     *
     * @param presThreshold the value for DSE_PIPE_BASEINFO.PRES_THRESHOLD
     *
     * @mbg.generated
     */
    public void setPresThreshold(Integer presThreshold) {
        this.presThreshold = presThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.DESIGN_DEPT
     *
     * @return the value of DSE_PIPE_BASEINFO.DESIGN_DEPT
     *
     * @mbg.generated
     */
    public String getDesignDept() {
        return designDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.DESIGN_DEPT
     *
     * @param designDept the value for DSE_PIPE_BASEINFO.DESIGN_DEPT
     *
     * @mbg.generated
     */
    public void setDesignDept(String designDept) {
        this.designDept = designDept == null ? null : designDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.CONSTRUCTION_DEPT
     *
     * @return the value of DSE_PIPE_BASEINFO.CONSTRUCTION_DEPT
     *
     * @mbg.generated
     */
    public String getConstructionDept() {
        return constructionDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.CONSTRUCTION_DEPT
     *
     * @param constructionDept the value for DSE_PIPE_BASEINFO.CONSTRUCTION_DEPT
     *
     * @mbg.generated
     */
    public void setConstructionDept(String constructionDept) {
        this.constructionDept = constructionDept == null ? null : constructionDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.SUPERVISOR_DEPT
     *
     * @return the value of DSE_PIPE_BASEINFO.SUPERVISOR_DEPT
     *
     * @mbg.generated
     */
    public String getSupervisorDept() {
        return supervisorDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.SUPERVISOR_DEPT
     *
     * @param supervisorDept the value for DSE_PIPE_BASEINFO.SUPERVISOR_DEPT
     *
     * @mbg.generated
     */
    public void setSupervisorDept(String supervisorDept) {
        this.supervisorDept = supervisorDept == null ? null : supervisorDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.BUILD_DEPT
     *
     * @return the value of DSE_PIPE_BASEINFO.BUILD_DEPT
     *
     * @mbg.generated
     */
    public String getBuildDept() {
        return buildDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.BUILD_DEPT
     *
     * @param buildDept the value for DSE_PIPE_BASEINFO.BUILD_DEPT
     *
     * @mbg.generated
     */
    public void setBuildDept(String buildDept) {
        this.buildDept = buildDept == null ? null : buildDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.LOCATION
     *
     * @return the value of DSE_PIPE_BASEINFO.LOCATION
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.LOCATION
     *
     * @param location the value for DSE_PIPE_BASEINFO.LOCATION
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.USE_YEAR
     *
     * @return the value of DSE_PIPE_BASEINFO.USE_YEAR
     *
     * @mbg.generated
     */
    public Short getUseYear() {
        return useYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.USE_YEAR
     *
     * @param useYear the value for DSE_PIPE_BASEINFO.USE_YEAR
     *
     * @mbg.generated
     */
    public void setUseYear(Short useYear) {
        this.useYear = useYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.TYPE
     *
     * @return the value of DSE_PIPE_BASEINFO.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.TYPE
     *
     * @param type the value for DSE_PIPE_BASEINFO.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.LOCATION_ID
     *
     * @return the value of DSE_PIPE_BASEINFO.LOCATION_ID
     *
     * @mbg.generated
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.LOCATION_ID
     *
     * @param locationId the value for DSE_PIPE_BASEINFO.LOCATION_ID
     *
     * @mbg.generated
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId == null ? null : locationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.CREATE_USER
     *
     * @return the value of DSE_PIPE_BASEINFO.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.CREATE_USER
     *
     * @param createUser the value for DSE_PIPE_BASEINFO.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.CREATE_TIME
     *
     * @return the value of DSE_PIPE_BASEINFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.CREATE_TIME
     *
     * @param createTime the value for DSE_PIPE_BASEINFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.UPDATE_TIME
     *
     * @return the value of DSE_PIPE_BASEINFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.UPDATE_TIME
     *
     * @param updateTime the value for DSE_PIPE_BASEINFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSE_PIPE_BASEINFO.UPDATE_USER
     *
     * @return the value of DSE_PIPE_BASEINFO.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSE_PIPE_BASEINFO.UPDATE_USER
     *
     * @param updateUser the value for DSE_PIPE_BASEINFO.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSE_PIPE_BASEINFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pipeName=").append(pipeName);
        sb.append(", code=").append(code);
        sb.append(", pipelineCode=").append(pipelineCode);
        sb.append(", pipelineName=").append(pipelineName);
        sb.append(", pipeMaterial=").append(pipeMaterial);
        sb.append(", pipeLength=").append(pipeLength);
        sb.append(", pipeRadius=").append(pipeRadius);
        sb.append(", pipeThickness=").append(pipeThickness);
        sb.append(", interfaceType=").append(interfaceType);
        sb.append(", startPoint=").append(startPoint);
        sb.append(", endPoint=").append(endPoint);
        sb.append(", companyId=").append(companyId);
        sb.append(", installTime=").append(installTime);
        sb.append(", status=").append(status);
        sb.append(", temperrature=").append(temperrature);
        sb.append(", transMedium=").append(transMedium);
        sb.append(", pressure=").append(pressure);
        sb.append(", flowThreshold=").append(flowThreshold);
        sb.append(", presThreshold=").append(presThreshold);
        sb.append(", designDept=").append(designDept);
        sb.append(", constructionDept=").append(constructionDept);
        sb.append(", supervisorDept=").append(supervisorDept);
        sb.append(", buildDept=").append(buildDept);
        sb.append(", location=").append(location);
        sb.append(", useYear=").append(useYear);
        sb.append(", type=").append(type);
        sb.append(", locationId=").append(locationId);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}