package com.cloud.springboot.entity;

import java.io.Serializable;
import java.util.Date;

public class TSysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.CARD_ID
     *
     * @mbg.generated
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.DUTY_LEVEL
     *
     * @mbg.generated
     */
    private String dutyLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.TECH_TITLE
     *
     * @mbg.generated
     */
    private String techTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.DEGREE
     *
     * @mbg.generated
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.TELEPHONE
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.BIRTHDAY
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.START_WORKDATE
     *
     * @mbg.generated
     */
    private Date startWorkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.SCHOOL
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.STUDY_MAJOR
     *
     * @mbg.generated
     */
    private String studyMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.BORN_PLACE
     *
     * @mbg.generated
     */
    private String bornPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.POLITICAL_STATUS
     *
     * @mbg.generated
     */
    private String politicalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.NATIONALITY
     *
     * @mbg.generated
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.ORDER_INDEX
     *
     * @mbg.generated
     */
    private Short orderIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.LOGIN_TIME
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.LOGOUT_TIME
     *
     * @mbg.generated
     */
    private Date logoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.LINE_STATUS
     *
     * @mbg.generated
     */
    private String lineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.CREATOR
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.LAST_UPDATOR
     *
     * @mbg.generated
     */
    private String lastUpdator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_USER.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_USER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.ID
     *
     * @return the value of T_SYS_USER.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.ID
     *
     * @param id the value for T_SYS_USER.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.USER_NAME
     *
     * @return the value of T_SYS_USER.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.USER_NAME
     *
     * @param userName the value for T_SYS_USER.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.PASSWORD
     *
     * @return the value of T_SYS_USER.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.PASSWORD
     *
     * @param password the value for T_SYS_USER.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.NAME
     *
     * @return the value of T_SYS_USER.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.NAME
     *
     * @param name the value for T_SYS_USER.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.CARD_ID
     *
     * @return the value of T_SYS_USER.CARD_ID
     *
     * @mbg.generated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.CARD_ID
     *
     * @param cardId the value for T_SYS_USER.CARD_ID
     *
     * @mbg.generated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.SEX
     *
     * @return the value of T_SYS_USER.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.SEX
     *
     * @param sex the value for T_SYS_USER.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.DUTY_LEVEL
     *
     * @return the value of T_SYS_USER.DUTY_LEVEL
     *
     * @mbg.generated
     */
    public String getDutyLevel() {
        return dutyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.DUTY_LEVEL
     *
     * @param dutyLevel the value for T_SYS_USER.DUTY_LEVEL
     *
     * @mbg.generated
     */
    public void setDutyLevel(String dutyLevel) {
        this.dutyLevel = dutyLevel == null ? null : dutyLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.TECH_TITLE
     *
     * @return the value of T_SYS_USER.TECH_TITLE
     *
     * @mbg.generated
     */
    public String getTechTitle() {
        return techTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.TECH_TITLE
     *
     * @param techTitle the value for T_SYS_USER.TECH_TITLE
     *
     * @mbg.generated
     */
    public void setTechTitle(String techTitle) {
        this.techTitle = techTitle == null ? null : techTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.DEGREE
     *
     * @return the value of T_SYS_USER.DEGREE
     *
     * @mbg.generated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.DEGREE
     *
     * @param degree the value for T_SYS_USER.DEGREE
     *
     * @mbg.generated
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.TELEPHONE
     *
     * @return the value of T_SYS_USER.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.TELEPHONE
     *
     * @param telephone the value for T_SYS_USER.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.MOBILE
     *
     * @return the value of T_SYS_USER.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.MOBILE
     *
     * @param mobile the value for T_SYS_USER.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.EMAIL
     *
     * @return the value of T_SYS_USER.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.EMAIL
     *
     * @param email the value for T_SYS_USER.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.BIRTHDAY
     *
     * @return the value of T_SYS_USER.BIRTHDAY
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.BIRTHDAY
     *
     * @param birthday the value for T_SYS_USER.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.START_WORKDATE
     *
     * @return the value of T_SYS_USER.START_WORKDATE
     *
     * @mbg.generated
     */
    public Date getStartWorkdate() {
        return startWorkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.START_WORKDATE
     *
     * @param startWorkdate the value for T_SYS_USER.START_WORKDATE
     *
     * @mbg.generated
     */
    public void setStartWorkdate(Date startWorkdate) {
        this.startWorkdate = startWorkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.SCHOOL
     *
     * @return the value of T_SYS_USER.SCHOOL
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.SCHOOL
     *
     * @param school the value for T_SYS_USER.SCHOOL
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.STUDY_MAJOR
     *
     * @return the value of T_SYS_USER.STUDY_MAJOR
     *
     * @mbg.generated
     */
    public String getStudyMajor() {
        return studyMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.STUDY_MAJOR
     *
     * @param studyMajor the value for T_SYS_USER.STUDY_MAJOR
     *
     * @mbg.generated
     */
    public void setStudyMajor(String studyMajor) {
        this.studyMajor = studyMajor == null ? null : studyMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.ADDRESS
     *
     * @return the value of T_SYS_USER.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.ADDRESS
     *
     * @param address the value for T_SYS_USER.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.BORN_PLACE
     *
     * @return the value of T_SYS_USER.BORN_PLACE
     *
     * @mbg.generated
     */
    public String getBornPlace() {
        return bornPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.BORN_PLACE
     *
     * @param bornPlace the value for T_SYS_USER.BORN_PLACE
     *
     * @mbg.generated
     */
    public void setBornPlace(String bornPlace) {
        this.bornPlace = bornPlace == null ? null : bornPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.POLITICAL_STATUS
     *
     * @return the value of T_SYS_USER.POLITICAL_STATUS
     *
     * @mbg.generated
     */
    public String getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.POLITICAL_STATUS
     *
     * @param politicalStatus the value for T_SYS_USER.POLITICAL_STATUS
     *
     * @mbg.generated
     */
    public void setPoliticalStatus(String politicalStatus) {
        this.politicalStatus = politicalStatus == null ? null : politicalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.NATIONALITY
     *
     * @return the value of T_SYS_USER.NATIONALITY
     *
     * @mbg.generated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.NATIONALITY
     *
     * @param nationality the value for T_SYS_USER.NATIONALITY
     *
     * @mbg.generated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.ORDER_INDEX
     *
     * @return the value of T_SYS_USER.ORDER_INDEX
     *
     * @mbg.generated
     */
    public Short getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.ORDER_INDEX
     *
     * @param orderIndex the value for T_SYS_USER.ORDER_INDEX
     *
     * @mbg.generated
     */
    public void setOrderIndex(Short orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.DESCRIPTION
     *
     * @return the value of T_SYS_USER.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.DESCRIPTION
     *
     * @param description the value for T_SYS_USER.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.STATUS
     *
     * @return the value of T_SYS_USER.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.STATUS
     *
     * @param status the value for T_SYS_USER.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.LOGIN_TIME
     *
     * @return the value of T_SYS_USER.LOGIN_TIME
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.LOGIN_TIME
     *
     * @param loginTime the value for T_SYS_USER.LOGIN_TIME
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.LOGOUT_TIME
     *
     * @return the value of T_SYS_USER.LOGOUT_TIME
     *
     * @mbg.generated
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.LOGOUT_TIME
     *
     * @param logoutTime the value for T_SYS_USER.LOGOUT_TIME
     *
     * @mbg.generated
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.LINE_STATUS
     *
     * @return the value of T_SYS_USER.LINE_STATUS
     *
     * @mbg.generated
     */
    public String getLineStatus() {
        return lineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.LINE_STATUS
     *
     * @param lineStatus the value for T_SYS_USER.LINE_STATUS
     *
     * @mbg.generated
     */
    public void setLineStatus(String lineStatus) {
        this.lineStatus = lineStatus == null ? null : lineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.CREATOR
     *
     * @return the value of T_SYS_USER.CREATOR
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.CREATOR
     *
     * @param creator the value for T_SYS_USER.CREATOR
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.CREATE_TIME
     *
     * @return the value of T_SYS_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.CREATE_TIME
     *
     * @param createTime the value for T_SYS_USER.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.LAST_UPDATOR
     *
     * @return the value of T_SYS_USER.LAST_UPDATOR
     *
     * @mbg.generated
     */
    public String getLastUpdator() {
        return lastUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.LAST_UPDATOR
     *
     * @param lastUpdator the value for T_SYS_USER.LAST_UPDATOR
     *
     * @mbg.generated
     */
    public void setLastUpdator(String lastUpdator) {
        this.lastUpdator = lastUpdator == null ? null : lastUpdator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.LAST_UPDATE_TIME
     *
     * @return the value of T_SYS_USER.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for T_SYS_USER.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.DEL_FLAG
     *
     * @return the value of T_SYS_USER.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.DEL_FLAG
     *
     * @param delFlag the value for T_SYS_USER.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_USER.TYPE
     *
     * @return the value of T_SYS_USER.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_USER.TYPE
     *
     * @param type the value for T_SYS_USER.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", cardId=").append(cardId);
        sb.append(", sex=").append(sex);
        sb.append(", dutyLevel=").append(dutyLevel);
        sb.append(", techTitle=").append(techTitle);
        sb.append(", degree=").append(degree);
        sb.append(", telephone=").append(telephone);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", birthday=").append(birthday);
        sb.append(", startWorkdate=").append(startWorkdate);
        sb.append(", school=").append(school);
        sb.append(", studyMajor=").append(studyMajor);
        sb.append(", address=").append(address);
        sb.append(", bornPlace=").append(bornPlace);
        sb.append(", politicalStatus=").append(politicalStatus);
        sb.append(", nationality=").append(nationality);
        sb.append(", orderIndex=").append(orderIndex);
        sb.append(", description=").append(description);
        sb.append(", status=").append(status);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", logoutTime=").append(logoutTime);
        sb.append(", lineStatus=").append(lineStatus);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdator=").append(lastUpdator);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}