package com.cloud.springboot.dao;

import com.cloud.springboot.entity.TSysRoleUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface TSysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user
     *
     * @mbg.generated
     */
    int insert(TSysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user
     *
     * @mbg.generated
     */
    TSysRoleUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user
     *
     * @mbg.generated
     */
    List<TSysRoleUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysRoleUser record);
}