package com.cloud.springboot.dao;

import com.cloud.springboot.entity.TSysRole;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    int insert(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    TSysRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    List<TSysRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysRole record);
}